name: build

on: [push, pull_request]

jobs:
  run-test:
    runs-on: macos-12
    strategy:
      matrix:
        destination: ["iOS Simulator,name=iPhone 14"]
        swift-version: [5.0]
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.1.2
          bundler-cache: true

      # - name: Check Cache
      #   uses: actions/cache@v2
      #   id: cocoapods-cache
      #   with:
      #     path: Pods
      #     key: ${{ runner.os }}-pods-${{ hashFiles('**/Podfile.lock') }}
      #     restore-keys: |
      #       ${{ runner.os }}-pods-

      - name: Swift Lint
        run: brew install swiftlint && swiftlint lint --strict

      # - name: Pod Install
      #   if: steps.cocoapods-cache.outputs.cache-hit != 'true'
      #   run: bundle exec pod install

      - name: Clean Xcode DerivedData
        run: |
          rm -rf ~/Library/Developer/Xcode/DerivedData/

      - name: Run Unit Tests
        env:
          DESTINATION: platform=${{ matrix.destination }}
          SWIFT_VERSION: ${{ matrix.swift-version }}
        run: |
          bundle exec fastlane test_ci
          bundle exec slather

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v3
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}

      - name: Generate plantuml
        uses: grassedge/generate-plantuml-action@v1.5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          path: PlantUML
          message: "chore: render PlantUML files"
